name: login

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  jobs:

  push:
    branches:
      - 'master'
      - 'main'

jobs:
  stop-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Stop docker
        run: |
          sudo systemctl stop docker
      -
        name: Login to GitHub Container Registry
        uses: ./
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  logout:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        logout:
          - false
          - true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Login to GitHub Container Registry
        uses: ./
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: ${{ matrix.logout }}

  dind:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      
        name: Login to GitHub Container Registry
        uses: ./
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: DinD
        uses: docker://docker
        with:
          entrypoint: docker
          args: pull ghcr.io/docker-ghactiontest/test
      -
        name: Pull private image
        run: |
          docker image prune -a -f >/dev/null 2>&1
          docker pull ghcr.io/docker-ghactiontest/test
